# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-FeedPP-Plugin-AddMP3
version:      0.02
version_from: lib/XML/FeedPP/Plugin/AddMP3.pm
installdirs:  site
requires:
    MP3::Info:                     1.22
    Path::Class:                   0.15
    XML::FeedPP:                   0.21

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
